//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazine.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magazine.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AreaId does not exists.
        /// </summary>
        internal static string AreaIdNotExists {
            get {
                return ResourceManager.GetString("AreaIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There can not be more than 4 CoAuthors per paper.
        /// </summary>
        internal static string CoAuthorNumExceeded {
            get {
                return ResourceManager.GetString("CoAuthorNumExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CoAuthors is null or empty.
        /// </summary>
        internal static string CoAuthorsNull {
            get {
                return ResourceManager.GetString("CoAuthorsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only chief editor may add areas.
        /// </summary>
        internal static string InvalidAddAreaUser {
            get {
                return ResourceManager.GetString("InvalidAddAreaUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only chief editor may add issues.
        /// </summary>
        internal static string InvalidAddIssueUser {
            get {
                return ResourceManager.GetString("InvalidAddIssueUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only Area editor may check evaluated papers.
        /// </summary>
        internal static string InvalidAreaEditor {
            get {
                return ResourceManager.GetString("InvalidAreaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Name is invalid.
        /// </summary>
        internal static string InvalidAreaName {
            get {
                return ResourceManager.GetString("InvalidAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email does not have a @ or a ..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only chief editor may evaluate papers.
        /// </summary>
        internal static string InvalidEvaluateEditor {
            get {
                return ResourceManager.GetString("InvalidEvaluateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magazine name may not be null nor empty.
        /// </summary>
        internal static string InvalidMagazineName {
            get {
                return ResourceManager.GetString("InvalidMagazineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue with this number already exists.
        /// </summary>
        internal static string IssueAlreadyExists {
            get {
                return ResourceManager.GetString("IssueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue must not be an empty one.
        /// </summary>
        internal static string IssueEmpty {
            get {
                return ResourceManager.GetString("IssueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Id already exists.
        /// </summary>
        internal static string IssueIdExists {
            get {
                return ResourceManager.GetString("IssueIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Id does not exist .
        /// </summary>
        internal static string IssueIdNotExists {
            get {
                return ResourceManager.GetString("IssueIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue does not exists.
        /// </summary>
        internal static string IssueNotExists {
            get {
                return ResourceManager.GetString("IssueNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue number is invalid, needs to be bigger or equal to 0.
        /// </summary>
        internal static string IssueNumberInvalid {
            get {
                return ResourceManager.GetString("IssueNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There exists no issue.
        /// </summary>
        internal static string IssuesNotExist {
            get {
                return ResourceManager.GetString("IssuesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation only valid for Logged in Users.
        /// </summary>
        internal static string LoggedOutUser {
            get {
                return ResourceManager.GetString("LoggedOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation only valid for Non Logged (Unregistered) Users.
        /// </summary>
        internal static string LoggedUser {
            get {
                return ResourceManager.GetString("LoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login already exists.
        /// </summary>
        internal static string LoginAlreadyExists {
            get {
                return ResourceManager.GetString("LoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is not magazine in the system.
        /// </summary>
        internal static string MagazineNotExists {
            get {
                return ResourceManager.GetString("MagazineNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More than 4 CoAuthors in the paper.
        /// </summary>
        internal static string MoreThan4CoAuthorsProvided {
            get {
                return ResourceManager.GetString("MoreThan4CoAuthorsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User is not a chief editor.
        /// </summary>
        internal static string NonChiefEditor {
            get {
                return ResourceManager.GetString("NonChiefEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date not valid.
        /// </summary>
        internal static string NotValidDate {
            get {
                return ResourceManager.GetString("NotValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Areas of interest are null or empty.
        /// </summary>
        internal static string NullAOI {
            get {
                return ResourceManager.GetString("NullAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area is null or empty.
        /// </summary>
        internal static string NullArea {
            get {
                return ResourceManager.GetString("NullArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Id is null or empty.
        /// </summary>
        internal static string NullAreaId {
            get {
                return ResourceManager.GetString("NullAreaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area name is null or empty.
        /// </summary>
        internal static string NullAreaName {
            get {
                return ResourceManager.GetString("NullAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There does not exist any area.
        /// </summary>
        internal static string NullAreas {
            get {
                return ResourceManager.GetString("NullAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments are null or empty.
        /// </summary>
        internal static string NullComments {
            get {
                return ResourceManager.GetString("NullComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date is null or empty.
        /// </summary>
        internal static string NullDate {
            get {
                return ResourceManager.GetString("NullDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is null or empty.
        /// </summary>
        internal static string NullEmail {
            get {
                return ResourceManager.GetString("NullEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assue number is null or empty.
        /// </summary>
        internal static string NullIssueNumber {
            get {
                return ResourceManager.GetString("NullIssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There does not exist any issue.
        /// </summary>
        internal static string NullIssues {
            get {
                return ResourceManager.GetString("NullIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login is null or empty.
        /// </summary>
        internal static string NullLogin {
            get {
                return ResourceManager.GetString("NullLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not any papers on this area.
        /// </summary>
        internal static string NullPapers {
            get {
                return ResourceManager.GetString("NullPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is null or empty.
        /// </summary>
        internal static string NullPassword {
            get {
                return ResourceManager.GetString("NullPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User surname is null or empty.
        /// </summary>
        internal static string NullSurname {
            get {
                return ResourceManager.GetString("NullSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title is null or empty.
        /// </summary>
        internal static string NullTitle {
            get {
                return ResourceManager.GetString("NullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The submission date is null.
        /// </summary>
        internal static string NullUploadDate {
            get {
                return ResourceManager.GetString("NullUploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User is null or empty.
        /// </summary>
        internal static string NullUser {
            get {
                return ResourceManager.GetString("NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI is null.
        /// </summary>
        internal static string NullUserId {
            get {
                return ResourceManager.GetString("NullUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in the title .
        /// </summary>
        internal static string NullValueTitle {
            get {
                return ResourceManager.GetString("NullValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper has been already evaluated.
        /// </summary>
        internal static string PaperAlreadyEvaluated {
            get {
                return ResourceManager.GetString("PaperAlreadyEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper already exists in that area.
        /// </summary>
        internal static string PaperAlreadyExists {
            get {
                return ResourceManager.GetString("PaperAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper has been already published.
        /// </summary>
        internal static string PaperAlreadyPublished {
            get {
                return ResourceManager.GetString("PaperAlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper Id does not exist.
        /// </summary>
        internal static string PaperIdNotExists {
            get {
                return ResourceManager.GetString("PaperIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper does not exist.
        /// </summary>
        internal static string PaperNotExists {
            get {
                return ResourceManager.GetString("PaperNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User does not exist.
        /// </summary>
        internal static string PaperNotInPublicationPending {
            get {
                return ResourceManager.GetString("PaperNotInPublicationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not match this user.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select an area in the list.
        /// </summary>
        internal static string SelectExistingArea {
            get {
                return ResourceManager.GetString("SelectExistingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a valid area.
        /// </summary>
        internal static string SelectNameArea {
            get {
                return ResourceManager.GetString("SelectNameArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Id already exists in this database.
        /// </summary>
        internal static string UserIdAlreadyExists {
            get {
                return ResourceManager.GetString("UserIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User is not an editor of any area.
        /// </summary>
        internal static string UserNotEditor {
            get {
                return ResourceManager.GetString("UserNotEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User does not exist.
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
